### ISSUE TITLE
New Containers, New Error, bad me #nolatesttag

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [pegasus-io/this-is-gravitee#1]
# The Issue, and its Context

### How to reproduce the issue

You 2 possibilities, to reproduce the issue : 

* You can simply run [the `0.0.1` release](https://github.com/pegasus-io/this-is-gravitee/releases/tag/0.0.1), which will give you a proof that this issue is raised on a recipe D. Brassely and myself verified it worked, see [this](https://github.com/gravitee-io/issues/issues/3545#issuecomment-614283736) (if you dissect `operations.sh`, and its `midnightSpecial` function, you will verify that fact) : 

```bash 
export DESIRED_VERSION=0.0.1
git clone git@github.com:pegasus-io/this-is-gravitee.git gravitee-on-earth
cd gravitee-on-earth/
git checkout ${DESIRED_VERSION}
./operations.sh
```

* Or you can use the following script, which will be a lot more simple for anyone to understand, and which reproduces the exact issue (look at how simple `./test-issue-1.sh` is, compared to `./operations.sh` ) :  

```bash 
export DESIRED_VERSION=TEST2_REPODUCTION_ISSUE_1
git clone git@github.com:pegasus-io/this-is-gravitee.git gravitee-earthling-issues
cd gravitee-earthling-issues/
git checkout ${DESIRED_VERSION}
./test-issue-1.sh
```

### The Context, and the Issue stdout

* 22 days ago from today, I made the `0.0.1` release, and it worked. I know that back then when I tested, 22 days ago, my release, I used an image that I docker pulled at least the day before, that is, at least 23 days ago. You can also check that my release `0.0.1` is based on `latest` version tag for docker images. And it was my mistake, to release 0.0.1 , based on a `latest` tag, instead of replacing it with a non-ambiguous semver tag.
* 22  days ago, a new image was pushed, and tagged latest, 22 days ago, which might explain why today, my 0.0.1 release fails at provisioning the full `Gravitee` stack. That is the case for example for : 
  * `graviteeio/management-api` : https://hub.docker.com/layers/graviteeio/management-api/latest/images/sha256-b26da4ea3e013a0c349dad137e9517336716d873ae9b638f3b6fb7d0be2c0e79?context=explore

* [release `0.0.1`](https://github.com/pegasus-io/this-is-gravitee/releases/tag/0.0.1) today fails, with the following errors, though it worked a few weeks ago : 

```bash 
The Launch Gravitee.io API Platform  Pulumi recipe is now generated...
Pulling mongodb         ... done
Pulling elasticsearch   ... done
Pulling apim_gateway    ... done
Pulling apim_management ... done
Pulling apim_portal     ... done
Pulling am_gateway      ... done
Pulling am_management   ... done
Pulling am_webui        ... done
Pulling traefik         ... done
Creating network "storage" with the default driver
Creating network "frontend" with the default driver
Creating this-is-gravitee_mongodb_1       ... done
Creating this-is-gravitee_elasticsearch_1 ... done
Creating this-is-gravitee_apim_management_1 ... error
Creating this-is-gravitee_apim_gateway_1    ... 
Creating this-is-gravitee_am_gateway_1      ... done
Creating this-is-gravitee_am_management_1   ... done
Creating this-is-gravitee_am_webui_1        ... 

Creating this-is-gravitee_apim_gateway_1    ... error
sed \"rootfs_linux.go:58: mounting \\\"/home/jbl/this-is-gravitee/gravitee/cacerts\\\" to rootfs \\\"/var/lib/docker/overlay2/3c638c91112e4f3cde752c3fa3906bd7b4268de8c210c54d24ccab3f3519b4c9/merged\\\" at \\\"/var/lib/docker/overlay2/3c638c91112e4f3cde752c3fa3906bd7b4268de8c210c54d24ccab3f3519b4c9/merged/etc/ssl/certs/java/cacerts\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for this-is-gravitee_apim_gateway_1  Cannot start service apim_gateway: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/jbl/this-is-gravitee/gravitee/cacerts\\\" to rootfs \\\"/var/lib/docker/overlay2/433282ae24e7cd9667210a8fe8b741dfd1339dbbf84b4d68f5fb37386f7ed1e6/merged\\\" at \\\"/var/lib/docker/overlay2/433282ae24e7cd9667210a8fe8b741dfd1339dbbf84b4d68f5fb37386f7ed1e6/merged/etc/ssl/certs/java/cacerts\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a fileCreating this-is-gravitee_am_webui_1        ... done

ERROR: for apim_management  Cannot start service apim_management: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/jbl/this-is-gravitee/gravitee/cacerts\\\" to rootfs \\\"/var/lib/docker/overlay2/3c638c91112e4f3cde752c3fa3906bd7b4268de8c210c54d24ccab3f3519b4c9/merged\\\" at \\\"/var/lib/docker/overlay2/3c638c91112e4f3cde752c3fa3906bd7b4268de8c210c54d24ccab3f3519b4c9/merged/etc/ssl/certs/java/cacerts\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for apim_gateway  Cannot start service apim_gateway: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/home/jbl/this-is-gravitee/gravitee/cacerts\\\" to rootfs \\\"/var/lib/docker/overlay2/433282ae24e7cd9667210a8fe8b741dfd1339dbbf84b4d68f5fb37386f7ed1e6/merged\\\" at \\\"/var/lib/docker/overlay2/433282ae24e7cd9667210a8fe8b741dfd1339dbbf84b4d68f5fb37386f7ed1e6/merged/etc/ssl/certs/java/cacerts\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
./operations.sh: line 104: docker-composer: command not found
jbl@pc-alienware-jbl:~/this-is-gravitee$ 
```
* The `./operations.sh: line 104: docker-composer: command not found` error message is not important here : this command is just a typo in the `./operations.sh` script, and it is the last error, so that the previous error will remain, even if that little typo is fixed.
* Only two services fail to start up, and subsequently, `traefik` never starts, since it `depends_on` those two services : 
  * `apim_gateway` :  that's the Gateway service of `Gravitee APIM`, based off of the OCI image  `graviteeio/gateway:latest` from _Docker Hub_ : 

```bash 
jbl@pc-alienware-jbl:~/gravitee-earthling-issues$ docker inspect graviteeio/gateway:latest| jq .[].Id
"sha256:8a70c1761deb912a20f3f86ba0cd8d2f4c6997775c35085b1f8099c24c35913f"
```

  * `apim_management` :  that's the API service of `Gravitee APIM`, based off of the OCI image  `graviteeio/management-api:latest` from _Docker Hub_.

```bash 
jbl@pc-alienware-jbl:~/gravitee-earthling-issues$ docker inspect graviteeio/am-management-api| jq .[].Id
"sha256:31267a14c09c3ec40f0dd2c13d51a2fb8ffe3bc2e134a6da81807556c1e42fbf"
```
```bash 
jbl@pc-alienware-jbl:~/gravitee-earthling-issues$ docker images
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
graviteeio/am-management-api                    latest              31267a14c09c        3 days ago          226MB
graviteeio/am-gateway                           latest              98a9cdb07109        3 days ago          215MB
graviteeio/am-management-ui                     latest              ff7f593358a3        3 days ago          46.1MB
graviteeio/management-ui                        latest              5e43ed1fad02        3 weeks ago         50.6MB
graviteeio/management-api                       latest              707364db8861        3 weeks ago         349MB
graviteeio/gateway                              latest              8a70c1761deb        3 weeks ago         325MB
traefik                                         v1.7                100389fa48aa        2 months ago        76.4MB
mongo                                           3.4                 f76f959b2a49        4 months ago        431MB
docker.elastic.co/elasticsearch/elasticsearch   6.3.1               fa7212eab151        23 months ago       783MB
```
  * those two have the same problem : 
    * compose error msg notifies us that we map some path on the docker host, say `PathOutside`, to a Path inside the container, say `PathInside`, and  : 
      * that either the  `PathInside` path does not exist inside container,  
      * or the  `PathOutside` path does not exist inside container,  
      * or that both `PathOutside` and `PathInside` path do not exist outisde, and inside container, respectivley.  We do have that case, since, you can guess, it was easy for me to check that  `PathOutside` does exists.
    * I was easy to check for each of those two paths, one of the three below assertions is true (and the other two are false) : 
       * Either The path does not exist
       * Or the path exists, and matches an `inode` which is a `file`, and not a `directory`
       * Or the path exists, and matches an `inode` which is a `directory`, and not a `file`
     * Now, we need to find out which of the three assertions above, is true for `PathInside` (in this case, you will check reporducing the issue, that `PathInside=/etc/ssl/certs/java/cacerts`) : 

# My Diagnosis up til now

* I will first check inode paths , which obviously are at the center of our little problem,  inside the containers that fail to start up. To do that I spawn up a "passivated" container instance from the docker images of theses services : 
  * test commands : 
```bash
# the Gravitee APIM API
docker run -it --name testjbl_apim_api graviteeio/management-api:latest ls -allh /etc/ssl/certs/java/cacerts
docker run -it --name testjbl_apim_api graviteeio/management-api:latest stat /etc/ssl/certs/java/cacerts

# the Gravitee APIM Gateway
docker run -it --name testjbl_apim_gw graviteeio/gateway:latest ls -allh /etc/ssl/certs/java/cacerts
docker run -it --name testjbl_apim_gw graviteeio/gateway:latest stat /etc/ssl/certs/java/cacerts
```
  * results : 
```bash
jbl@pc-alienware-jbl:~/gravitee-earthling-issues$ docker run -it --name testjbl_apim_api graviteeio/management-api:latest ls -allh /etc/ssl/certs/java/cacerts
-r--r--r--    1 root     root      171.2K Oct 24  2018 /etc/ssl/certs/java/cacerts
jbl@pc-alienware-jbl:~/gravitee-earthling-issues$ docker run -it --name testjbl_apim_api graviteeio/management-api:latest stat /etc/ssl/certs/java/cacerts
  File: /etc/ssl/certs/java/cacerts
  Size: 175337    	Blocks: 344        IO Block: 4096   regular file
Device: 851h/2129d	Inode: 931034      Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-10-24 22:32:16.000000000
Modify: 2018-10-24 22:32:16.000000000
Change: 2020-05-29 15:06:41.000000000

jbl@pc-alienware-jbl:~/gravitee-earthling-issues$ docker run -it --name testjbl_apim_gw graviteeio/gateway:latest ls -allh /etc/ssl/certs/java/cacerts
-r--r--r--    1 root     root      171.2K Oct 24  2018 /etc/ssl/certs/java/cacerts
jbl@pc-alienware-jbl:~/gravitee-earthling-issues$ docker run -it --name testjbl_apim_gw graviteeio/gateway:latest stat /etc/ssl/certs/java/cacerts
  File: /etc/ssl/certs/java/cacerts
  Size: 175337    	Blocks: 344        IO Block: 4096   regular file
Device: 851h/2129d	Inode: 931034      Links: 1
Access: (0444/-r--r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-10-24 22:32:16.000000000
Modify: 2018-10-24 22:32:16.000000000
Change: 2020-05-29 15:06:41.000000000

```

Inside the `apim_management` service : 

* Does `PathInside=/etc/ssl/certs/java/cacerts` exists ? **Yes**.
* Does `PathInside=/etc/ssl/certs/java/cacerts` matches a file ? **Yes**.
* Does `PathInside=/etc/ssl/certs/java/cacerts` matches a directory ? **No**.

Inside the `apim_gateway` service : 

* Does `PathInside=/etc/ssl/certs/java/cacerts` exists ? **Yes**.
* Does `PathInside=/etc/ssl/certs/java/cacerts` matches a file ? **Yes**.
* Does `PathInside=/etc/ssl/certs/java/cacerts` matches a directory ? **No**.

* Outside, on the docker host : 

  * Does `PathOutside=$PWD/gravitee/cacerts` exists ? **Yes** (reproduce the issue, and run the `ls $PWD/gravitee/cacerts` command
  * Does `PathOutside=$PWD/gravitee/cacerts` matches a file ? **No**.
  * Does `PathOutside=$PWD/gravitee/cacerts` matches a directory ? **Yes**.

# My first attempt to fix the issue on my own

Ok, so now, I know, that `PathOutside` is a directory, while `/etc/ssl/certs/java/cacerts` is a file. That is a first, and easy issue to solve. All I have to do, is to replace, in `docker-compose.yml`, `"$PWD/gravitee/cacerts:/etc/ssl/certs/java/cacerts"`, by `"$PWD/gravitee/:/etc/ssl/certs/java/"`.

* here is the result I got, and to reproduce that, from scratch, all you have to do is copy paste this : 

```bash
# reproduce the issue

export DESIRED_VERSION=TEST2_REPODUCTION_ISSUE_1
git clone git@github.com:pegasus-io/this-is-gravitee.git gravitee-earthling-issues
cd gravitee-earthling-issues/
git checkout ${DESIRED_VERSION}
./test-issue-1.sh

# apply the fix

sed -i "s#\$PWD/gravitee/cacerts:/etc/ssl/certs/java/cacerts#$PWD/gravitee:/etc/ssl/certs/java#g" docker-compose.yml

# re-launch the docker-compose

docker-compose down --rmi all && docker system prune -f --all && docker-compose up -d 
```
* Alright, once that fix is applied, the file/directory issue is fixed. So that was my mistake, and my `0.0.1` release was rotten by that issue.
* But at taht point, you will be able to check for yourself, that there is now another issue, which is that `Gravtiee APIM` faisl to connect to `elasticsearch` : 

```bash
jbl@pc-alienware-jbl:~/gravitee-earthling-issues$ docker-compose logs  apim_management|grep -B10 'Caused by:'|grep -B10 'Exception'|head -n 15
apim_management_1  | 19:30:16.817 [graviteeio-node] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available alert: 
apim_management_1  | 19:30:16.817 [graviteeio-node] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available service_discovery: 
apim_management_1  | 19:30:16.817 [graviteeio-node] INFO  i.g.p.c.internal.PluginRegistryImpl - 	> consul-service-discovery [1.1.1] has been loaded
apim_management_1  | 19:30:16.817 [graviteeio-node] INFO  i.g.p.c.internal.PluginRegistryImpl - List of available protocol: 
apim_management_1  | 19:30:16.817 [graviteeio-node] INFO  i.g.p.c.internal.PluginEventListener - All plugins have been loaded. Installing...
apim_management_1  | 19:30:16.817 [graviteeio-node] INFO  i.g.p.c.internal.PluginEventListener - Installing REPOSITORY plugins...
apim_management_1  | 19:30:16.822 [graviteeio-node] INFO  i.g.m.r.p.RepositoryPluginHandler - Register a new repository: repository-elasticsearch [io.gravitee.repository.elasticsearch.ElasticsearchRepository]
apim_management_1  | 19:30:16.823 [graviteeio-node] INFO  i.g.m.r.p.RepositoryPluginHandler - Repository [ANALYTICS] loaded by elasticsearch
apim_management_1  | 19:30:17.470 [vert.x-eventloop-thread-3] ERROR i.g.e.client.http.HttpClient - Unable to get a connection to Elasticsearch
apim_management_1  | io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: elasticsearch/192.168.16.5:9200
apim_management_1  | Caused by: java.net.ConnectException: Connection refused
--
apim_management_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
apim_management_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
apim_management_1  | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
jbl@pc-alienware-jbl:~/gravitee-earthling-issues$ 
```

* Hum, why does that happen ?
  * In my case, (and it will be diffrent for you, basauce you have a different LAN where you work) `Gravitee APIM API/management` is trying to connect to `elasticsearch`, using `192.168.16.5:9200`, but the problem is, that the `192.168.16.5` IP address doe snot exists in my LAN (actually, it is my Orange Box, just a French ISP)
* Even better, see for yourself my net interface on the machine where my docker-compose sits :
```bash
jbl@pc-alienware-jbl:~/gravitee-earthling-issues$ ip addr|grep 168
    inet 192.168.0.49/24 brd 192.168.0.255 scope global enp5s0
    inet 192.168.1.28/24 brd 192.168.1.255 scope global enp4s0
    inet 192.168.16.1/20 brd 192.168.31.255 scope global br-138df426c9ed
    inet 192.168.32.1/20 brd 192.168.47.255 scope global br-c7ac83b5f72c
```
* Okay, so now, you will check for yourself, that Elasticsearch is not up and healthy, just execute `docker-compose logs -f elasticsearch`
* And finally, I fixed this `elasticsearch` issue, out of executing this : 

```bash 
sudo chmod a+rw -R ./data && docker-compose restart elasticsearch && docker-compose logs -f elasticsearch
```
* Let's see now if `Gravitee APIM` 's REST API can connect Elasticsearch, now : 

```bash
# -- just restarting and logs of Gravitee APIM API
```

# Enjoy 

![](https://github.com/Jean-Baptiste-Lasselle/for-fellow-developers/raw/master/docuementation/impr.ecrans/gravitee/GRAVITEE_APIM_VERSION_3_UP_2020-05-29%2021-56-23.png)
* YESSSSSS!!! everything is fixed now, and you can enjoy Gravitee APIM version 3, just released a few days ago, from the excellent, brilliant Gravitee Team!  :D 
* And I am so glad, to show my `CTO` once again , that it was, me, who made a rotten release, 
* That when the Gravitee team release anything, it is battle tested and reliable
* that I should never, ever give a release that is not battle tested, 
* that it is a mistake I will never, ever make again, because it is stupid, always happens at the wrong time, and does not ever cost more than a day to make a release, and battle test it, while I this week made my `CTO`, and my whole Team, lose 2 days, and that is the lesser worst case (losing just 2 days) 
* and that I feel so much better, pointing at that one mistake I fell into, rather than making my `CTO` doubt about the solutions I advise him to take : 
  * My Mistake, not Gravitee's at all, which is extremely rigourous : 
  * You, and I, both know, that when there is a true problem of the software reliablility, You don't fix it with the simple steps I used above, driven by analysis.

So once again, Thank you Gravitee Team, for your excellent, rigourous work.

**Comment by Jean-Baptiste-Lasselle** [comment]
# Pour reproduire  à l'identitque, l'issue 

```bash 
export DESIRED_VERSION=TEST2_REPODUCTION_ISSUE_1

git clone git@github.com:pegasus-io/this-is-gravitee.git gravitee-earthling-issues

cd gravitee-earthling-issues/

git checkout ${DESIRED_VERSION}

./test-issue-1.sh
```

**Comment by Jean-Baptiste-Lasselle** [comment]
TODO : 
* [ ] make a new release including the present fix.
* [ ] give it for free to community, send by email to gravitee great team

**Comment by Jean-Baptiste-Lasselle** [comment]
Note to the reader : I also ran the `sudo sysctl -w vm.max_map_count=262144` on the docker host, before running all those tests.
